name: e_library
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0  # Using an older version compatible with SDK 2.15.1
  html: ^0.15.0
  get_it: ^7.6.0

  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
